workers: {
  portwatcher: '',

  base_linux_ubuntu_1804_x86_64: '',
  base_10_5_ppc: '',
  base_10_6_x86_64: '',
  base_10_7_x86_64: '',
  base_10_8_x86_64: '',
  base_10_9_x86_64: '',
  base_10_10_x86_64: '',
  base_10_11_x86_64: '',
  base_10_12_x86_64: '',
  base_10_13_x86_64: '',
  base_10_14_x86_64: '',
  base_10_15_x86_64: '',

  ports_linux_ubuntu_1804_x86_64: '',
  ports_10_5_ppc_legacy: '',
  ports_10_6_i386: '',
  ports_10_6_x86_64: '',
  ports_10_7_x86_64: '',
  ports_10_8_x86_64: '',
  ports_10_9_x86_64: '',
  ports_10_10_x86_64: '',
  ports_10_11_x86_64: '',
  ports_10_12_x86_64: '',
  ports_10_13_x86_64: '',
  ports_10_14_x86_64: '',
  ports_10_15_x86_64: '',
}

config: {
  production: true,
  info: {
    title:      'MacPorts',
    titleURL:   'https://www.macports.org',
    url:        'http://build.macports.org',
    httpport:   8010,
    workerport: 9989,
  },
  urls: {
    base:  'https://github.com/macports/macports-base.git',
    ports: 'https://github.com/mojca/macports-ports.git',
    mpbb:  'https://github.com/macports/mpbb.git',
    infra: 'https://github.com/macports/macports-infrastructure.git',
    guide: 'https://github.com/macports/macports-guide.git',
    www:   'https://github.com/macports/macports-www.git',
    archive_public:  'http://packages.macports.org',
    archive_private: 'https://packages-private.macports.org',
  },
  paths: {
    prefix: '/opt/local',
    tools:  '/opt/local-tools',
  },
  database: {
    # 'sqlite:///state.sqlite'
  },
}
  
builders: {
  watcher: {
    worker: portwatcher,
  },
  ports:
    -
      name: ports-linux
      worker: ports_linux_ubuntu_1804_x86_64
    -
      name: ports-10_6_x86_64
      worker: ports_10_6_x86_64
      # TODO: potentially overwrite prefix, tools
    -
      name: ports-10_7_x86_64
      worker: ports_10_7_x86_64
}
